"""Generate client contracts from canonical Pydantic models; no network required."""
import inspect
import json
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'packages/shared/python'))
from pydantic import BaseModel
from selery_shared import models

def ts(s):
    if '$ref' in s:return s['$ref'].split('/')[-1]
    if 'anyOf' in s:return ' | '.join(ts(x) for x in s['anyOf'])
    if 'enum' in s:return ' | '.join(json.dumps(x) for x in s['enum'])
    if 'const' in s:return json.dumps(s['const'])
    t=s.get('type')
    if t=='array':return f'Array<{ts(s["items"])}>'
    if t=='object':return 'Record<string, '+(ts(s['additionalProperties']) if isinstance(s.get('additionalProperties'),dict) else 'unknown')+'>'
    return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(t,'unknown')

def zs(s):
    if '$ref' in s:return 'z.lazy(() => '+s['$ref'].split('/')[-1]+'Schema)'
    if 'anyOf' in s:return 'z.union(['+', '.join(zs(x) for x in s['anyOf'])+'])'
    if 'enum' in s:return 'z.enum('+json.dumps(s['enum'])+')'
    if 'const' in s:return 'z.literal('+json.dumps(s['const'])+')'
    t=s.get('type')
    if t=='array':return 'z.array('+zs(s['items'])+')'
    if t=='object':return 'z.record('+ (zs(s['additionalProperties']) if isinstance(s.get('additionalProperties'),dict) else 'z.unknown()') +')'
    result={'string':'z.string()','integer':'z.number().int().finite()','number':'z.number().finite()','boolean':'z.boolean()','null':'z.null()'}.get(t,'z.unknown()')
    for key,method in [('minimum','min'),('maximum','max'),('exclusiveMinimum','gt'),('exclusiveMaximum','lt'),('minLength','min'),('maxLength','max')]:
        if key in s:result+=f'.{method}({s[key]})'
    if 'pattern' in s:result+='.regex(new RegExp('+json.dumps(s['pattern'])+'))'
    return result

schemas={}
for name,cls in inspect.getmembers(models,inspect.isclass):
    if issubclass(cls,BaseModel) and cls.__module__==models.__name__ and name!='Contract':
        schema=cls.model_json_schema()
        schemas.update(schema.pop('$defs',{}));schemas[name]=schema
lines=['// GENERATED by scripts/generate_contracts.py. Do not edit.', 'import { z } from "zod";','']
for name,s in sorted(schemas.items()):
    if 'properties' in s:
        lines.append(f'export type {name} = {{')
        # API serialization emits model defaults, so response fields are always present.
        for key,prop in s['properties'].items():lines.append(f'  {json.dumps(key)}: {ts(prop)};')
        lines.append('};')
    else:lines.append(f'export type {name} = {ts(s)};')
for name,s in sorted(schemas.items()):
    if 'properties' in s:
        parts=[json.dumps(k)+': '+zs(v) for k,v in s['properties'].items()]
        lines.append(f'export const {name}Schema: z.ZodType<{name}> = z.object({{'+', '.join(parts)+'}).strict();')
    else:lines.append(f'export const {name}Schema: z.ZodType<{name}> = {zs(s)};')
target=ROOT/'packages/shared/src/contracts.ts'
content='\n'.join(lines)+'\n'
json_target=ROOT/'packages/shared/contracts.json'
json_content=json.dumps(schemas,indent=2)+'\n'
if '--check' in sys.argv:
    if not target.exists() or target.read_text()!=content or not json_target.exists() or json_target.read_text()!=json_content:raise SystemExit('Generated contracts are stale')
else:
    target.write_text(content)
    json_target.write_text(json_content)
